// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEdMv3wNo56q5i9Qtvu-9F9IbD2Hb1NqQ',
    appId: '1:740643891493:web:96e919ac0ae191e98f12cc',
    messagingSenderId: '740643891493',
    projectId: 'cosmetic-app-e51bc',
    authDomain: 'cosmetic-app-e51bc.firebaseapp.com',
    storageBucket: 'cosmetic-app-e51bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmxdcCjsp9xXCtcssLT0itSF0thYPWmo',
    appId: '1:740643891493:android:9d8c9f7cfe47021e8f12cc',
    messagingSenderId: '740643891493',
    projectId: 'cosmetic-app-e51bc',
    storageBucket: 'cosmetic-app-e51bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsKFWXHKy_mlu8OksJRlqdk82Us3HGio',
    appId: '1:740643891493:ios:ca3144c5468cc8b28f12cc',
    messagingSenderId: '740643891493',
    projectId: 'cosmetic-app-e51bc',
    storageBucket: 'cosmetic-app-e51bc.appspot.com',
    iosClientId: '740643891493-e60e69t94tcaoaipvb61d8vdq831l1tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosmeticApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChsKFWXHKy_mlu8OksJRlqdk82Us3HGio',
    appId: '1:740643891493:ios:ca3144c5468cc8b28f12cc',
    messagingSenderId: '740643891493',
    projectId: 'cosmetic-app-e51bc',
    storageBucket: 'cosmetic-app-e51bc.appspot.com',
    iosClientId: '740643891493-e60e69t94tcaoaipvb61d8vdq831l1tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosmeticApp',
  );
}
